# Generated by Django 4.2.10 on 2024-02-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulepost",
            name="post_detail",
            field=models.TextField(blank=True, null=True),
        ),
    ]
