# Generated by Django 4.2.9 on 2024-02-24 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schedule", "0004_alter_schedulepost_post_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("IG", "Instagram"),
                            ("FB", "Facebook"),
                            ("X", "Twitter"),
                        ],
                        default="IG",
                        max_length=15,
                    ),
                ),
                ("credentials", models.JSONField()),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
