# Generated by Django 4.2.9 on 2024-02-24 05:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0005_platformauth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedulepost",
            name="post_detail",
        ),
    ]
