# Generated by Django 4.2.9 on 2024-02-24 05:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0006_remove_schedulepost_post_detail"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulepost",
            name="schedule_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
