# Generated by Django 4.2.9 on 2024-02-24 05:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PlatformAuth",
        ),
    ]
